version: '3'

services:
  web:
    build: .
    environment:
      - PORT=8080
    ports:
      - "8081:8080"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

